"""
Survey every archite gene in the ACTIVE mod set.

The altar's lottery draws from genes with biostatArc > 0, and the outcome tiers
are bands over biostatMet / biostatCpx. Picking those band cutoffs without
seeing the real distribution would be guesswork, so this dumps the actual pool.

Only mods listed in config/ModsConfig.xml are scanned - a gene in a subscribed
but disabled mod is not in the pool and must not appear here.

Run:  python tools/survey_archite.py
Writes: docs/archite-gene-pool.md
"""

import os
import re
import sys

DATA = r"C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Data"
WORKSHOP = r"C:\Program Files (x86)\Steam\steamapps\workshop\content\294100"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STALE = re.compile(r"[\\/]1\.[0-5][\\/]")
GENEDEF = re.compile(r"<GeneDef[^>]*>(.*?)</GeneDef>", re.S)


def tag(body, name, default=None):
    """Biostats omitted from a GeneDef default to 0 in game, not to 'unknown'.
    biostatMet in particular is left out of almost every archite gene."""
    m = re.search(r"<%s>(-?[\d.]+)</%s>" % (name, name), body)
    return int(float(m.group(1))) if m else default


def text(body, name):
    m = re.search(r"<%s>(.*?)</%s>" % (name, name), body, re.S)
    return m.group(1).strip() if m else None


def active_package_ids():
    cfg = os.path.join(REPO, "config", "ModsConfig.xml")
    with open(cfg, encoding="utf-8-sig") as fh:
        return {p.lower() for p in re.findall(r"<li>([^<]+)</li>", fh.read())}


def workshop_folders_for(active):
    """Map active packageIds onto the workshop folders that declare them."""
    found = []
    if not os.path.isdir(WORKSHOP):
        return found
    for entry in os.listdir(WORKSHOP):
        about = os.path.join(WORKSHOP, entry, "About", "About.xml")
        if not os.path.isfile(about):
            continue
        try:
            with open(about, encoding="utf-8-sig", errors="ignore") as fh:
                blob = fh.read()
        except OSError:
            continue
        pid = re.search(r"<packageId>([^<]+)</packageId>", blob)
        name = re.search(r"<name>([^<]+)</name>", blob)
        if pid and pid.group(1).strip().lower() in active:
            found.append((os.path.join(WORKSHOP, entry),
                          name.group(1).strip() if name else entry))
    return found


def harvest(root, source, out):
    for dirpath, _, filenames in os.walk(root):
        if STALE.search(dirpath):
            continue
        for fn in filenames:
            if not fn.endswith(".xml"):
                continue
            try:
                with open(os.path.join(dirpath, fn),
                          encoding="utf-8-sig", errors="ignore") as fh:
                    blob = fh.read()
            except OSError:
                continue
            if "<GeneDef" not in blob:
                continue
            for m in GENEDEF.finditer(blob):
                body = m.group(1)
                arc = tag(body, "biostatArc")
                if not arc or arc <= 0:
                    continue
                defname = text(body, "defName")
                if not defname:
                    continue
                out[defname] = {
                    "label": text(body, "label") or "",
                    "cpx": tag(body, "biostatCpx", 0),
                    "met": tag(body, "biostatMet", 0),
                    "arc": arc,
                    "source": source,
                }


def main():
    active = active_package_ids()
    genes = {}

    # Core and the DLCs ship inside Data/; every one of them is always active.
    for sub in sorted(os.listdir(DATA)):
        full = os.path.join(DATA, sub)
        if os.path.isdir(full):
            harvest(full, sub, genes)

    mods = workshop_folders_for(active)
    for folder, name in mods:
        harvest(folder, name, genes)

    harvest(REPO, "Archinity", genes)

    rows = sorted(genes.items(),
                  key=lambda kv: (-(kv[1]["cpx"] or 0), kv[1]["met"], kv[0]))

    lines = []
    lines.append("# Archite gene pool\n")
    lines.append("Every gene with `biostatArc > 0` in the **active** mod set - "
                 "i.e. the exact pool the altar's lottery can draw from.\n")
    lines.append("Sorted by **complexity** (highest first), then metabolic "
                 "cost. Archite genes are priced almost entirely in "
                 "complexity - biostatMet is 0 for nearly all of them, so "
                 "cpx is the only usable power proxy.\n")
    lines.append("Generated by `tools/survey_archite.py`. "
                 "Regenerate after any mod change.\n")
    lines.append("\n| defName | label | met | cpx | arc | source |")
    lines.append("|---|---|---:|---:|---:|---|")
    for defname, g in rows:
        lines.append("| `%s` | %s | %s | %s | %s | %s |" % (
            defname, g["label"],
            "-" if g["met"] is None else g["met"],
            "-" if g["cpx"] is None else g["cpx"],
            g["arc"], g["source"]))

    # Distribution, so the tier cutoffs can be chosen against real numbers.
    buckets = {}
    for _, g in rows:
        buckets.setdefault(g["cpx"], 0)
        buckets[g["cpx"]] += 1
    lines.append("\n## Distribution by complexity\n")
    lines.append("| cpx | count |")
    lines.append("|---:|---:|")
    for cpx in sorted(buckets, reverse=True):
        lines.append("| %s | %d |" % (cpx, buckets[cpx]))

    by_source = {}
    for _, g in rows:
        by_source[g["source"]] = by_source.get(g["source"], 0) + 1
    lines.append("\n## By source\n")
    lines.append("| source | genes |")
    lines.append("|---|---:|")
    for src in sorted(by_source, key=lambda s: -by_source[s]):
        lines.append("| %s | %d |" % (src, by_source[src]))

    out = os.path.join(REPO, "docs", "archite-gene-pool.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("active mods matched : %d" % len(mods))
    print("archite genes found : %d" % len(rows))
    print("written             : %s" % out)
    missing = []
    if missing:
        print("\nNOTE - biostats not declared inline (likely inherited); "
              "verify by hand:")
        for d in missing:
            print("  %s" % d)


if __name__ == "__main__":
    sys.exit(main())
